### PR TITLE
fix: Use local RASA X URL if it connects to local Rasa OSS

### LINKED ISSUE #25: Model training lasts forever over Rasa X UI
**Describe the bug**
If you connect a Rasa OSS to Rasa X using the `connect rasa` command, model training triggered via Rasa UI X lasts forever. It is caused by an incorrect URL that is used by Rasa OSS to send results back.

### PR DESCRIPTION
**Pull request by tczekajlo**
If the `connect rasa` commend is used, the Rasa OSS should be able to connect to Rasa X by using a URL passed in a call. To achieve that, the rasa-x service has to be exposed on a NodePort and the `RASA_X_HOST` value in the rasa-x deployment has to be changed to point to ta URL that uses the NodePort.

Fixes #25

### CODE REVIEW

File: pkg/helm/default_values.go [hunk 1]
```diff
@@ -178,6 +178,30 @@ func ValuesPostgreSQLNodePort() map[string]interface{} {
 	return values
 }
 
+// ValuesRasaXNodePort returns helm vales which set the rasa-x service type to NodePort.
```
Comment (virtualroot) [inline pkg/helm/default_values.go:181]:
```suggestion
// ValuesRasaXNodePort returns helm values which set the rasa-x service type to NodePort.
```

File: pkg/helm/default_values.go [hunk 2]
```diff
@@ -178,6 +178,30 @@ func ValuesPostgreSQLNodePort() map[string]interface{} {
...
+			"service": map[string]interface{}{
+				"type": "NodePort",
+			},
+		},
+	}
+
+	return values
+}
+
+// ValuesSetRasaXHost returns helm vales which set the RASA_X_HOST env variable for the rasa-x deployment.
```
Comment (virtualroot) [inline pkg/helm/default_values.go:194]:
```suggestion
// ValuesSetRasaXHost returns helm values which set the RASA_X_HOST env variable for the rasa-x deployment.
```

**Review by virtualroot — APPROVED** [review]
